export type IOCRResponse = {
  amount: number | null;
  category: string;
};

export const EXPENSE_CATEGORIES = {
  RENT: 'Rent',
  FOOD: 'Food',
  EDUCATION: 'Education',
  TRAVEL: 'Travel',
  GAS: 'Gas',
  OIL: 'Oil',
  MEDICAL: 'Medical',
  SHOPPING: 'Shopping',
  ENTERTAINMENT: 'Entertainment',
  OTHERS: 'others',
} as const;

export type IExpenseCategory =
  (typeof EXPENSE_CATEGORIES)[keyof typeof EXPENSE_CATEGORIES];

export const CATEGORY_KEYWORDS: Record<IExpenseCategory, string[]> = {
  [EXPENSE_CATEGORIES.RENT]: [
    'rent',
    'lease',
    'landlord',
    'housing',
    'apartment',
  ],
  [EXPENSE_CATEGORIES.FOOD]: [
    'restaurant',
    'cafe',
    'food',
    'dine',
    'lunch',
    'dinner',
    'breakfast',
    'grocery',
    'supermarket',
    'mcdonalds',
    'starbucks',
    'kfc',
    'burger',
    'pizza',
    'eats',
  ],
  [EXPENSE_CATEGORIES.EDUCATION]: [
    'school',
    'university',
    'college',
    'tuition',
    'course',
    'training',
    'book',
    'library',
    'exam',
    'education',
  ],
  [EXPENSE_CATEGORIES.TRAVEL]: [
    'flight',
    'hotel',
    'travel',
    'airline',
    'accommodation',
    'airbnb',
    'booking',
    'trip',
    'vacation',
    'passport',
  ],
  [EXPENSE_CATEGORIES.GAS]: [
    'gas',
    'fuel',
    'petrol',
    'shell',
    'exxon',
    'bp',
    'chevron',
    'filling station',
    'station',
  ],
  [EXPENSE_CATEGORIES.OIL]: [
    'oil',
    'lubricant',
    'engine oil',
    'castrol',
    'mobil',
    'valvoline',
  ],
  [EXPENSE_CATEGORIES.MEDICAL]: [
    'hospital',
    'pharmacy',
    'doctor',
    'medical',
    'medicine',
    'health',
    'clinic',
    'dentist',
    'drugstore',
    'prescription',
  ],
  [EXPENSE_CATEGORIES.SHOPPING]: [
    'store',
    'shop',
    'retail',
    'purchase',
    'goods',
    'market',
    'amazon',
    'ebay',
    'walmart',
    'target',
    'clothing',
    'fashion',
  ],
  [EXPENSE_CATEGORIES.ENTERTAINMENT]: [
    'movie',
    'cinema',
    'concert',
    'event',
    'ticket',
    'leisure',
    'netflix',
    'spotify',
    'game',
    'club',
    'theatre',
  ],
  [EXPENSE_CATEGORIES.OTHERS]: [],
};
